# Generated by Django 3.2.3 on 2021-06-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_markmodel_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.citymodel'),
        ),
    ]
