# Generated by Django 3.2.3 on 2021-06-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_projectmodel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='AverageMark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='ShowMainPage',
            field=models.BooleanField(default=False),
        ),
    ]
